TRAIN:
  ENABLE: True
  DATASET: Epickitchens
  BATCH_SIZE: 12
  EVAL_PERIOD: 2
  CHECKPOINT_PERIOD: 2
  AUTO_RESUME: True
  FINETUNE: True
  CHECKPOINT_EPOCH_RESET: True
  CHECKPOINT_FILE_PATH:
MIXUP:
  MIXUP_ALPHA: 0.0
DATA:
  NUM_FRAMES: 32
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [320, 384]
  TRAIN_CROP_SIZE: 288
  TEST_CROP_SIZE: 288
  INPUT_CHANNEL_NUM: [3, 3]
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.229, 0.224, 0.225]
  FRAME_SAMPLING: 'like omnivore'
  USE_RAND_AUGMENT: True
SOLVER:
  BASE_LR: 4e-4
  LR_POLICY: cosine
  LRS: [1, 0.1, 0.01]
  STEPS: [0, 30, 40]
  MAX_EPOCH: 50
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.004
  WARMUP_EPOCHS: 1.0
  OPTIMIZING_METHOD: adamw
  USE_MIXED_PRECISION: False
  SMOOTHING: 0.2
  GRAD_ACCUMULATION_ITER: 4
MODEL:
  NUM_CLASSES: [3806]
  ARCH: omnivore_swinB_imagenet21k_288
  MODEL_NAME: Omnivore
  LOSS_FUNC: label_smoothing_cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True
  DATASET: epickitchens
  BATCH_SIZE: 2
  NUM_SPATIAL_CROPS: 1
  NUM_ENSEMBLE_VIEWS: 1
  FEATURE_EXTRACTION: False
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
EPICKITCHENS:
  TRAIN_PLUS_VAL: False
NUM_GPUS: 1     # ✓✓✓✓✓✓
OUTPUT_DIR: output   # ✓✓✓✓✓✓
